<?php

	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(1, 'Some people want it to happen, some wish it would happen, others MAKE it happen.', 'Michael Jordan'),
(2, 'The best way out is always through.', 'Robert Frost'),
(3, 'Whatever the mind can conceive and believe, the mind can achieve.', 'Napoleon Hill'),
(4, 'You become what you think about.', 'Napoleon Hill'),
(5, 'Keep your mind fixed on what you want in life, not on what you don\'t want.', 'Napoleon Hill'),
(6, 'No one has yet discovered the limitations of the power of his own mind.', 'Napoleon Hill'),
(7, 'The only limitations are those we set up in our own minds.', 'Napoleon Hill'),
(8, 'The only limitations that can hold you back are those you willingly accept as unbeatable.', 'Napoleon Hill'),
(9, 'You\'ll never know the miracles your mind can perform until you acquire the habit of casting off these imaginary shackles.', 'Napoleon Hill'),
(10, 'Whatever your mind feeds upon, your mind attracts to you.', 'Napoleon Hill'),
(11, 'The mind grows only through use, and it atrophies through idleness.', 'Napoleon Hill'),
(12, 'You can do it if you believe you can.', 'Napoleon Hill'),
(13, 'If you don\'t believe in yourself, how can you ask others to do so?', 'Napoleon Hill'),
(14, 'You have within you all the power you need with which to get whatever you want or need in this world, and about the best way to avail yourself of this power is to believe in yourself.', 'Napoleon Hill'),
(15, 'All success begins with definiteness of purpose.', 'Napoleon Hill'),
(16, 'The starting point of all achievement is DESIRE.', 'Napoleon Hill'),
(17, 'In every adversity or defeat there is a seed of equal or greater benefit.', 'Napoleon Hill'),
(18, 'It isn\'t defeat, but rather your mental attitude toward it, that whips you.', 'Napoleon Hill'),
(19, 'A quitter never wins and a winner never quits.', 'Napoleon Hill'),
(20, 'Sound character is our greatest asset because it provides the power with which we may ride the emergencies of life instead of going down under them.', 'Napoleon Hill'),
(21, 'Faith is the only know antidote for failure!', 'Napoleon Hill'),
(22, 'When you get yourself under complete control, you can be your own boss.', 'Napoleon Hill'),
(23, 'Good intentions are useless until they are expressed in appropriate action.', 'Napoleon Hill'),
(24, 'Don\'t wait. The time will never be just right.', 'Napoleon Hill'),
(25, 'If you really are smarter than others, show them with your actions.', 'Napoleon Hill'),
(26, 'Concentrate upon a given desire until that desire becomes a burning obsession.', 'Napoleon Hill'),
(27, 'Form the habit of going the extra mile, giving service that is not expected, for this attracts friends, clients, and supporters in many ways.', 'Napoleon Hill'),
(28, 'Do your job precisely as if you were your own boss, and sooner or later you will be.', 'Napoleon Hill'),
(29, 'Your mental attitude is the most dependable key to your personality.', 'Napoleon Hill'),
(30, 'Self-respect is the best means of getting the respect of others.', 'Napoleon Hill'),
(31, 'A negative mind spawns only negative ideas.', 'Napoleon Hill'),
(32, 'If life hands you a lemon, don\'t complain, but instead make lemonade to sell those who are thirsty from complaining.', 'Napoleon Hill'),
(33, 'Success is good at any age, but the sooner you find it, the longer you will enjoy it.', 'Napoleon Hill'),
(34, 'If you can\'t do great things, do small things in a great way.', 'Napoleon Hill'),
(35, 'More gold has been mined from the mind of men than the earth itself.', 'Napoleon Hill'),
(36, 'The way of success is the way of continuous pursuit of knowledge.', 'Napoleon Hill'),
(37, 'Success requires no explanations. Failure permits no alibis.', 'Napoleon Hill'),
(38, 'Enthusiasm is the one great emotion which automatically guarantees that your point of view will be positive!', 'Napoleon Hill'),
(39, 'No one can keep you down but yourself.', 'Napoleon Hill'),
(40, 'Failure seems to be nature\'s plan for preparing us for great responsibilities.', 'Napoleon Hill'),
(41, 'The worst thing about worry is that it attracts a whole flock of relatives.', 'Napoleon Hill'),
(42, 'A positive mental attitude is basic to all achievement.', 'Napoleon Hill'),
(43, 'If you are sure you are right, you need not worry what the world thinks.', 'Napoleon Hill'),
(44, 'If you don\'t know why you failed, you are no wiser than when you began.', 'Napoleon Hill'),
(45, 'The imagination is the workshop of the soul, where are shaped all the plans for individual achievement.', 'Napoleon Hill'),
(46, 'Opportunity has a queer way of stalking the person who can recognize it and is ready to embrace it.', 'Napoleon Hill'),
(47, 'A resourceful person will always make opportunity fit his or her needs.', 'Napoleon Hill'),
(48, 'Change your mental attitude, and the world around you will change accordingly.', 'Napoleon Hill'),
(49, 'Constancy of purpose is the first principle of success.', 'Napoleon Hill'),
(50, 'Sometimes it is wiser to join forces with opponents than to fight them.', 'Napoleon Hill')
	");
	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(51, 'Wisdom consists in knowing what not to want as well as what to want.', 'Napoleon Hill'),
(52, 'Nature yields her most profound secrets to those who are determined to uncover them.', 'Napoleon Hill'),
(53, 'Patience, persistence, and perspiration make an unbeatable combination for success.', 'Napoleon Hill'),
(54, 'There is an abundance of everything for the person who knows what he wants.', 'Napoleon Hill'),
(55, 'Great achievement is usually born of great sacrifice, and is never the result of selfishness.', 'Napoleon Hill'),
(56, 'Remember that your real wealth can be measured, not by what you have, but, by what you are.', 'Napoleon Hill'),
(57, 'The only safe way to boast is by constructive actions.', 'Napoleon Hill'),
(58, 'One sound idea is all you need to achieve success.', 'Napoleon Hill'),
(59, 'Every failure brings with it the seed of an equivalent success.', 'Napoleon Hill'),
(60, 'Kindle anew in your mind the fire of hope, faith, courage, and tolerance.', 'Napoleon Hill'),
(61, 'Set your goals for the day, week, month, year, rest of your life, and then live in the moment.', 'James Altucher'),
(62, 'What if every moment we turned the facts of our lives into poetry? To give up trying to assign meaning and turn all of our periods into question marks.', 'James Altucher'),
(63, 'You have absolute control over but one thing, and that is your thoughts.', 'James Allen'),
(64, 'Everything in the universe is resolved into your own inward experience. It matters little what is without, for it is all a reflection of your own state of consciousness.', 'James Allen'),
(65, 'Do you wish for kindness? Be kind. Do you ask for truth? Be true. What you give of yourself you find. Your world is a reflex of you.', 'James Allen'),
(66, 'Mere wishing brings nothing but disappointment, it is living that tells.', 'James Allen'),
(67, 'The reward of our work is not what we get, but what we become.', 'Paulo Coelho'),
(68, 'Life is like riding a bicycle. To keep your balance, you must keep moving', 'Albert Einstein'),
(69, 'A startup is a human institution designed to create a product or service under conditions of extreme uncertainty.', 'Eric Ries'),
(70, 'Lean thinking defines value as providing benefit to the customer; anything else is waste.', 'Eric Ries'),
(71, 'Is it possible that we could have discovered how flawed our assumptions were without building anything?', 'Eric Ries'),
(72, 'The effort that is not absolutely necessary for learning what customers want can be eliminated.', 'Eric Ries'),
(73, 'It\'s easy to kid yourself about what you think customers want.', 'Eric Ries'),
(74, 'One of the most important lessons of the scientific method: if you cannot fail, you cannot learn.', 'Eric Ries'),
(75, 'You cannot be sure you really understand any part of any business problem unless you go and see for yourself firsthand.', 'Eric Ries'),
(76, 'No amount of design can anticipate the many complexities of bringing a product to life in the real world.', 'Eric Ries'),
(77, 'Be authentic, be creative, and generate leads into your sales funnel by providing valuable content and advice.', 'Jim Cockrum'),
(78, 'The challenge of remaining human in the onslaught of technology must remain utmost in our minds.', 'James Altucher'),
(79, 'Amateurs sit and wait for inspiration, the rest of us just get up and go to work.', 'Stephen King'),
(80, 'If you spend too much time thinking about a thing, you\'ll never get it done.', 'Bruce Lee'),
(81, 'Whenever you are asked if you can do a job, tell \'em, \"Certainly I can!\" Then get busy and find out how to do it.', 'Theodore Roosevelt'),
(82, 'Concentrate all your thoughts upon the work in hand. The Sun\'s rays do not burn until brought to a focus.', 'Alexander Graham Bell'),
(83, 'Focus on being productive instead of busy.', 'Tim Ferriss'),
(84, 'Success is often achieved by those who don\'t know that failure is inevitable.', 'Coco Chanel'),
(85, 'Absorb what is useful, reject what is useless, add what is specifically your own.', 'Bruce Lee'),
(86, 'You\'ve got to say, I think that if I keep working at this and want it badly enough I can have it. It\'s called perseverance.', 'Lee Iacocca'),
(87, 'Effective performance is preceded by painstaking preparation.', 'Brian Tracy'),
(88, 'The desire of knowledge, like the thirst for riches, increases ever with the acquisition of it.', 'Laurence Sterne'),
(89, 'We either make ourselves miserable, or we make ourselves strong. The amount of work is the same.', 'Carlos Castaneda'),
(90, 'If you love life, don\'t waste time, for time is what life is made up of.', 'Bruce Lee'),
(91, 'It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.', 'Charles Darwin'),
(92, 'Action is the foundational key to all success.', 'Pablo Picasso'),
(93, 'While one person hesitates because he feels inferior, the other is busy making mistakes and becoming superior.', 'Henry Link'),
(94, 'Whether you think you can or whether you think you can\'t, you\'re right!', 'Henry Ford'),
(95, 'Failure is simply an opportunity to begin again, this time more intelligently.', 'Henry Ford'),
(96, 'The only real mistake is the one from which we learn nothing.', 'Henry Ford'),
(97, 'Obstacles are those frightful things you see when you take your eyes off your goals.', 'Henry Ford'),
(98, 'Vision without execution is just hallucination.', 'Henry Ford'),
(99, 'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.', 'Henry Ford'),
(100, 'Coming together is the beginning. Keeping together is progress. Working together is success.', 'Henry Ford')
	");
	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(101, 'One of the greatest discoveries a person makes, one of their great surprises, is to find they can do what they were afraid they couldn\'t do.', 'Henry Ford'),
(102, 'The only real security that a man can have in this world is a reserve of knowledge, experience and ability.', 'Henry Ford'),
(103, 'The whole secret of a successful life is to find out what is one\'s destiny to do, and then do it.', 'Henry Ford'),
(104, 'There is no man living who isn\'t capable of doing more than he thinks he can do.', 'Henry Ford'),
(105, 'If you always do what you\'ve always done, you\'ll always get what you\'ve always got.', 'Henry Ford'),
(106, 'Even a mistake may turn out to be the one thing necessary to a worthwhile achievement.', 'Henry Ford'),
(107, 'If everyone is moving forward together, then success takes care of itself.', 'Henry Ford'),
(108, 'Begin with the determination to succeed, and the work is half done already.', 'Henry Ford'),
(109, 'An idealist is a person who helps other people to be prosperous.', 'Henry Ford'),
(110, 'Do not look for approval except for the consciousness of doing your best.', 'Andrew Carnegie'),
(111, 'Here is the prime condition of success: Concentrate your energy, thought and capital exclusively upon the business in which you are engaged.', 'Andrew Carnegie'),
(112, 'The way to become rich is to put all your eggs in one basket and then watch that basket.', 'Andrew Carnegie'),
(113, 'If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success.', 'John D. Rockefeller'),
(114, 'Don\'t be afraid to give up the good to go for the great.', 'John D. Rockefeller'),
(115, 'Next to doing the right thing, the most important thing is to let people know you are doing the right thing.', 'John D. Rockefeller'),
(116, 'Singleness of purpose is one of the chief essentials for success in life, no matter what may be one\'s aim.', 'John D. Rockefeller'),
(117, 'Try to turn every disaster into an opportunity.', 'John D. Rockefeller'),
(118, 'Many of life\'s failures are people who did not realize how close they were to success when they gave up.', 'Thomas A. Edison'),
(119, 'Five percent of the people think; ten percent of the people think they think; and the other eighty-five percent would rather die than think.', 'Thomas A. Edison'),
(120, 'We often miss opportunity because it\'s dressed in overalls and looks like work', 'Thomas A. Edison'),
(121, 'Genius is one percent inspiration, ninety-nine percent perspiration.', 'Thomas A. Edison'),
(122, 'The three great essentials to achieve anything worthwhile are, first, hard work; second, stick-to-itiveness; third, common sense.', 'Thomas A. Edison'),
(123, 'If we all did the things we are really capable of doing, we would literally astound ourselves.', 'Thomas A. Edison'),
(124, 'When you have exhausted all possibilities, remember this - you haven\'t.', 'Thomas A. Edison'),
(125, 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.', 'Thomas A. Edison'),
(126, 'There are no rules here -- we\'re trying to accomplish something.', 'Thomas A. Edison'),
(127, 'Show me a thoroughly satisfied man - and I will show you a failure.', 'Thomas A. Edison'),
(128, 'To do much clear thinking a person must arrange for regular periods of solitude when they can concentrate and indulge the imagination without distraction.', 'Thomas A. Edison'),
(129, 'Nearly every person who develops an idea works at it up to the point where it looks impossible, and then gets discouraged. That\'s not the place to become discouraged.', 'Thomas A. Edison'),
(130, 'The first requisite for success is the ability to apply your physical and mental energies to one problem incessantly without growing weary.', 'Thomas A. Edison'),
(131, 'A good intention, with a bad approach, often leads to a poor result.', 'Thomas A. Edison'),
(132, 'Two things are infinite: the universe and human stupidity; and I\'m not sure about the universe.', 'Albert Einstein'),
(133, 'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.', 'Albert Einstein'),
(134, 'Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.', 'Albert Einstein'),
(135, 'Anyone who has never made a mistake has never tried anything new.', 'Albert Einstein'),
(136, 'When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That\'s relativity.', 'Albert Einstein'),
(137, 'A clever person solves a problem. A wise person avoids it.', 'Albert Einstein'),
(138, 'Reality is merely an illusion, albeit a very persistent one.', 'Albert Einstein'),
(139, 'Education is what remains after one has forgotten what one has learned in school.', 'Albert Einstein'),
(140, 'The important thing is to not stop questioning. Curiosity has its own reason for existence.', 'Albert Einstein'),
(141, 'The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.', 'Albert Einstein'),
(142, 'If A is a success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your mouth shut!', 'Albert Einstein'),
(143, 'In the middle of difficulty lies opportunity', 'Albert Einstein'),
(144, 'The important thing is not to stop questioning. Curiosity has its own reason for existing.', 'Albert Einstein'),
(145, 'I\'d rather be an optimist and a fool than a pessimist and right.', 'Albert Einstein'),
(146, 'When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.', 'Alexander Graham Bell'),
(147, 'A man, as a general rule, owes very little to what he is born with - a man is what he makes of himself.', 'Alexander Graham Bell'),
(148, 'Leave the beaten track behind occasionally and dive into the woods. Every time you do, you will be certain to find something you have never seen before.', 'Alexander Graham Bell'),
(149, 'What this power is I cannot say; all I know is that it exists and it becomes available only when a man is in that state of mind in which he knows exactly what he wants and is fully determined not to quit until he finds it.', 'Alexander Graham Bell'),
(150, 'It doesn\'t matter where you are coming from. All that matters is where you are going.', 'Brian Tracy')
	");
	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(151, 'Luck is quite predictable. If you want more luck, take more chances. Be more active. Show up more often.', 'Brian Tracy'),
(152, 'The key to success is to focus our conscious mind on things we desire not things we fear.', 'Brian Tracy'),
(153, 'Whatever you believe with feeling becomes your reality.', 'Brian Tracy'),
(154, 'The more credit you give away, the more will come back to you. The more you help others, the more they will want to help you.', 'Brian Tracy'),
(155, 'You have within you right now, everything you need to deal with whatever the world can throw at you.', 'Brian Tracy'),
(156, 'The greatest gift that you can give to others is the gift of unconditional love and acceptance.', 'Brian Tracy'),
(157, 'People with clear, written goals, accomplish far more in a shorter period of time than people without them could ever imagine.', 'Brian Tracy'),
(158, 'Mistakes are always forgivable, if one has the courage to admit them.', 'Bruce Lee'),
(159, 'A goal is not always meant to be reached, it often serves simply as something to aim at.', 'Bruce Lee'),
(160, 'Notice that the stiffest tree is most easily cracked, while the bamboo or willow survives by bending with the wind.', 'Bruce Lee'),
(161, 'A wise man can learn more from a foolish question than a fool can learn from a wise answer.', 'Bruce Lee'),
(162, 'As you think, so shall you become.', 'Bruce Lee'),
(163, 'The key to immortality is first living a life worth remembering.', 'Bruce Lee'),
(164, 'A man of knowledge lives by acting, not by thinking about acting.', 'Carlos Castaneda'),
(165, 'You have everything needed for the extravagant journey that is your life.', 'Carlos Castaneda'),
(166, 'A path is only a path, and there is no affront, to oneself or to others, in dropping it if that is what your heart tells you.', 'Carlos Castaneda'),
(167, 'The basic difference between an ordinary man and a warrior is that a warrior takes everything as a challenge while an ordinary man takes everything as a blessing or a curse.', 'Carlos Castaneda'),
(168, 'In a world where death is the hunter, my friend, there is no time for regrets or doubts. There is only time for decisions.', 'Carlos Castaneda'),
(169, 'A warrior cannot complain or regret anything. His life is an endless challenge, and challenges cannot possibly be good or bad. Challenges are simply challenges.', 'Carlos Castaneda'),
(170, 'Forget the self and you will fear nothing, in whatever level or awareness you find yourself to be.', 'Carlos Castaneda'),
(171, 'The highest possible stage in moral culture is when we recognize that we ought to control our thoughts.', 'Charles Darwin'),
(172, 'A man\'s friendships are one of the best measures of his worth.', 'Charles Darwin'),
(173, 'In the long history of humankind...those who learned to collaborate and improvise most effectively have prevailed.', 'Charles Darwin'),
(174, 'Simplicity is the keynote of all true elegance.', 'Coco Chanel'),
(175, 'Don\'t spend time beating on a wall, hoping to transform it into a door.', 'Coco Chanel'),
(176, 'Circumstances do not make the man, they reveal him.', 'James Allen'),
(177, 'You are today where your thoughts have brought you; you will be tomorrow where your thoughts take you.', 'James Allen'),
(178, 'Men are anxious to improve their circumstances, but are unwilling to improve themselves; they therefore remain bound.', 'James Allen'),
(179, 'Only worry about your own happiness, which doesn\'t have to be limited by anyone else\'s stupidity unless you allow it to be.', 'James Altucher'),
(180, 'In solitude the mind gains strength and learns to lean upon itself.', 'Laurence Sterne'),
(181, 'Nothing is so perfectly amusing as a total change of ideas.', 'Laurence Sterne'),
(182, 'The discipline of writing something down is the first step toward making it happen.', 'Lee Iacocca'),
(183, 'We are continually faced by great opportunities brilliantly disguised as insoluble problems.', 'Lee Iacocca'),
(184, 'In times of great stress or adversity, it\'s always best to keep busy, to plow your anger and your energy into something positive.', 'Lee Iacocca'),
(185, 'If you want to make good use of your time, you\'ve got to know what\'s most important and then give it all you\'ve got.', 'Lee Iacocca'),
(186, 'You can have brilliant ideas, but if you can\'t get them across, your ideas won\'t get you anywhere.', 'Lee Iacocca'),
(187, 'You have to expect things of yourself before you can do them.', 'Michael Jordan'),
(188, 'Always turn a negative situation into a positive situation.', 'Michael Jordan'),
(189, 'Just play. Have fun. Enjoy the game.', 'Michael Jordan'),
(190, 'Obstacles don\'t have to stop you. If you run into a wall, don\'t turn around and give up. Figure out how to climb it, go through it, or work around it.', 'Michael Jordan'),
(191, 'Everybody has talent, but ability takes hard work.', 'Michael Jordan'),
(192, 'Never say never, because limits, like fears, are often just an illusion.', 'Michael Jordan'),
(193, 'If you do the work you get rewarded. There are no shortcuts in life.', 'Michael Jordan'),
(194, 'Everything you can imagine is real.', 'Pablo Picasso'),
(195, 'Only put off until tomorrow what you are willing to die having left undone.', 'Pablo Picasso'),
(196, 'Every act of creation is first of all an act of destruction.', 'Pablo Picasso'),
(197, 'Art is the lie that enables us to realize the truth.', 'Pablo Picasso'),
(198, 'Learn the rules like a pro, so you can break them like an artist.', 'Pablo Picasso'),
(199, 'The meaning of life is to find your gift. The purpose of life is to give it away.', 'Pablo Picasso'),
(200, 'Be brave. Take risks. Nothing can substitute experience.', 'Paulo Coelho')
	");
	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(201, 'There is only one thing that makes a dream impossible to achieve: the fear of failure.', 'Paulo Coelho'),
(202, 'Tell your heart that the fear of suffering is worse than the suffering itself.', 'Paulo Coelho'),
(203, 'No heart has ever suffered when it goes in search of its dream.', 'Paulo Coelho'),
(204, 'Happiness makes up in height for what it lacks in length.', 'Robert Frost'),
(205, 'In three words I can sum up everything I\'ve learned about life: it goes on.', 'Robert Frost'),
(206, 'Two roads diverged in a wood, and I, I took the one less traveled by, and that has made all the difference.', 'Robert Frost'),
(207, 'A good objective of leadership is to help those who are doing poorly to do well, and to help those who are doing well do even better.', 'Jim Rohn'),
(208, 'People will not bear it when advice is violently given, even if it is well founded. Hearts are flowers; they remain open to the softly falling dew, but shut up in the violent downpour of rain.', 'John Paul Richter'),
(209, 'It takes as much energy to wish as it does to plan.', 'Eleanor Roosevelt'),
(210, 'Until we can manage time, we can manage nothing else.', 'Peter Drucker'),
(211, 'Worry is interest paid on trouble before it comes due.', 'William Ralph Inge'),
(212, 'It does not matter how slowly you go up, so long as you don\'t stop.', 'Confucius'),
(213, 'Knowing is not enough; we must apply. Willing is not enough; we must do.', 'Johann Wolfgang Von Goethe'),
(214, 'Luck is a dividend of sweat. The more you sweat, the luckier you get.', 'Ray Kroc'),
(215, 'If you don\'t fail now and again, it\'s a sign you\'re playing it safe.', 'Woody Allen'),
(216, 'Whatever you can do or dream you can, begin it. Boldness has genius, power and magic in it.', 'Johann Wolfgang Von Goethe'),
(217, 'If you can find a path with no obstacles, it probably doesn\'t lead anywhere.', 'Frank A. Clark'),
(218, 'Everyone is trying to accomplish something big, not realizing that life is made up of little things.', 'Frank A. Clark'),
(219, 'It\'s hard to detect good luck - it looks so much like something you\'ve earned.', 'Frank A. Clark'),
(220, 'Real generosity is doing something nice for someone who will never find out.', 'Frank A. Clark'),
(221, 'Why not upset the apple cart? If you don\'t, the apples will rot anyway.', 'Frank A. Clark'),
(222, 'Make everything as simple as possible, but not simpler.', 'Albert Einstein'),
(223, 'When you dare to dream, dare to follow that dream; dare to suffer through the pain, sacrifice, self-doubts and friction from the world.', 'Dr. Laura Schlessinger'),
(224, 'Don\'t worry so much about your self-esteem. Worry more about your character. Integrity is its own reward.', 'Dr. Laura Schlessinger'),
(225, 'The reward for doing right is mostly an internal phenomenon: self-respect, dignity, integrity, and self- esteem.', 'Dr. Laura Schlessinger'),
(226, 'This is all you have. This is not a dry run. This is your life. If you want to fritter it away with your fears, then you will fritter it away, but you won\'t get it back later.', 'Dr. Laura Schlessinger'),
(227, 'Courage is not limited to the battlefield. The real tests of courage are much quieter. They are the inner tests, like enduring pain when the room is empty, or standing alone when you\'re misunderstood.', 'Charles Swindoll'),
(228, 'Create a definite plan for carrying out your desire and begin at once, whether you\'re ready or not, to put this plan into action.', 'Napoleon Hill'),
(229, 'You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.', 'Eleanor Roosevelt'),
(230, 'You must do the thing you think you cannot do.', 'Eleanor Roosevelt'),
(231, 'Nothing is more expensive than a missed opportunity.', 'H. Jackson Brown'),
(232, 'The price of greatness is responsibility.', 'Winston Churchill'),
(233, 'Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill'),
(234, 'Success consists of going from failure to failure without loss of enthusiasm.', 'Winston Churchill'),
(235, 'Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.', 'Winston Churchill'),
(236, 'To improve is to change; to be perfect is to change often.', 'Winston Churchill'),
(237, 'Continuous effort - not strength or intelligence - is the key to unlocking our potential.', 'Winston Churchill'),
(238, 'A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.', 'Winston Churchill'),
(239, 'We make a living by what we get, but we make a life by what we give.', 'Winston Churchill'),
(240, 'Victory at all costs, victory in spite of all terror, victory however long and hard the road may be; for without victory, there is no survival.', 'Winston Churchill'),
(241, 'Feeling gratitude and not expressing it is like wrapping a present and not giving it.', 'William Arthur Ward'),
(242, 'By altering out attitudes we can alter our lives.', 'Zig Ziglar'),
(243, 'Success is not a destination, it is a journey.', 'Zig Ziglar'),
(244, 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'Albert Schweitzer'),
(245, 'Go as far as you can see; when you get there, you\'ll be able to see farther.', 'Zig Ziglar'),
(246, 'No matter how you feel, get up, dress up, show up, and never give up.', 'Zig Ziglar'),
(247, 'What you do today can change all the tomorrows of your life', 'Zig Ziglar'),
(248, 'We cannot start over, but we can begin now, and make a new ending.', 'Zig Ziglar'),
(249, 'Getting knocked down in life is a given. Getting up and moving forward is a choice!', 'Zig Ziglar'),
(250, 'The only difference between successful people and unsuccessful people is extraordinary determination.', 'Mary Kay Ash')
	");
	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(251, 'You can\'t calm the storm so stop trying. What you can do is calm yourself. The storm will pass.', 'Zig Ziglar'),
(252, 'The foundation stones for a balanced success are honesty, character, integrity, faith, love, and loyalty.', 'Zig Ziglar'),
(253, 'You don\'t have to be great to start, but you have to start to be great.', 'Zig Ziglar'),
(254, 'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.', 'Helen Keller'),
(255, 'Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved.', 'Helen Keller'),
(256, 'Your success and happiness lies in you. Resolve to keep happy, and your joy and you shall form an invincible host against difficulties.', 'Helen Keller'),
(257, 'The most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.', 'Helen Keller'),
(258, 'When we do the best that we can, we never know what miracle is wrought in our life, or in the life of another.', 'Helen Keller'),
(259, 'Many persons have a wrong idea of what constitutes true happiness. It is not attained through self-gratification but through fidelity to a worthy purpose.', 'Helen Keller'),
(260, 'Either write something worth reading or do something worth writing.', 'Benjamin Franklin'),
(261, 'Focus your messages on the results you expect, not on the methods for doing the job.', 'Marty Brounstein'),
(262, 'In the confrontation between the stream and the rock, the stream always wins, not through strength but by perseverance.', 'H. Jackson Brown'),
(263, 'The mind is its own place, and in itself can make a heav\'n of hell and a hell of a heav\'n.', 'John Milton'),
(264, 'Strength does not come from physical capacity. It comes from indomitable will.', 'Mahatma Gandhi'),
(265, 'Don\'t be afraid to be unique or speak your mind, because that\'s what makes you different from everyone else.', 'Dave Thomas'),
(266, 'Accept the challenges so that you may feel the exhilaration of victory.', 'George S. Patton'),
(267, 'If you can dream it, then you can achieve it.', 'Zig Ziglar'),
(268, 'You will get all you want in life if you help enough other people get what they want.', 'Zig Ziglar'),
(269, 'Chance favors those in motion.', 'James A. Austin'),
(270, 'To sit back and let fate play its hand out and never influence it is not the way man was meant to operate.', 'John Glenn'),
(271, 'As long as you\'re going to be thinking anyway, think big.', 'Donald Trump'),
(272, 'We cannot change our past. We can not change the fact that people act in a certain way. We can not change the inevitable. The only thing we can do is play on the one string we have, and that is our attitude.', 'Charles Swindoll'),
(273, 'When you have vision it affects your attitude. Your attitude is optimistic rather than pessimistic.', 'Charles Swindoll'),
(274, 'The difference between something good and something great is attention to detail.', 'Charles Swindoll'),
(275, 'The secret of living a life of excellence is merely a matter of thinking thoughts of excellence. Really, it\'s a matter of programming our minds with the kind of information that will set us free.', 'Charles Swindoll'),
(276, 'We are all faced with a series of great opportunities brilliantly disguised as impossible situations.', 'Charles Swindoll'),
(277, 'Attitude is more important than the past, than education, than money, than circumstances, than what people do or say. It is more important than appearance, giftedness, or skill.', 'Charles Swindoll'),
(278, 'By failing to prepare, you are preparing to fail.', 'Benjamin Franklin'),
(279, 'Without continual growth and progress, such words as improvement, achievement, and success have no meaning.', 'Benjamin Franklin'),
(280, 'It takes many good deeds to build a good reputation, and only one bad one to lose it.', 'Benjamin Franklin'),
(281, 'Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones.', 'Benjamin Franklin'),
(282, 'To succeed, jump as quickly at opportunities as you do at conclusions.', 'Benjamin Franklin'),
(283, 'There are two ways of being happy: We must either diminish our wants or augment our means.', 'Benjamin Franklin'),
(284, 'The doorstep to the temple of wisdom is a knowledge of our own ignorance.', 'Benjamin Franklin'),
(285, 'One today is worth two tomorrows.', 'Benjamin Franklin'),
(286, 'You earn your reputation by the things you do every day.', 'Dave Thomas'),
(287, 'Whatâ€™s the secret to success? Itâ€™s no secret. You need a winning attitude, honesty and integrity, and a burning desire to succeed.', 'Dave Thomas'),
(288, 'Thereâ€™s no one to stop you but yourself.', 'Dave Thomas'),
(289, 'You can do what you want to do. You can be what you want to be.', 'Dave Thomas'),
(290, 'Hard work is good for the soul, and it keeps you from feeling sorry for yourself because you donâ€™t have time.', 'Dave Thomas'),
(291, 'We should never take our freedoms for granted, and we should seize every opportunity presented to us.', 'Dave Thomas'),
(292, 'A great leader is someone who practices what they preach. They lead by example, create a sense of loyalty and teamwork, and are active in the community sharing their success with those in need.', 'Dave Thomas'),
(293, 'Believe in your dream. People may tell you that you won\'t make it, that you\'re wasting your time. If you keep your dream in mind, have done your research and are willing to work hard, you can make it come true.', 'Dave Thomas'),
(294, 'Luck does not come around often. So when it does, be sure to take full advantage of it, even if it means working very hard.', 'Donald Trump'),
(295, 'Part of being a winner is knowing when enough is enough. Sometimes you have to give up the fight and walk away, and move on to something that\'s more productive.', 'Donald Trump'),
(296, 'In the end, you\'re measured not by how much you undertake but by what you finally accomplish.', 'Donald Trump'),
(297, 'What separates the winners from the losers is how a person reacts to each new twist of fate.', 'Donald Trump'),
(298, 'If you\'re interested in \'balancing\' work and pleasure, stop trying to balance them. Instead make your work more pleasurable.', 'Donald Trump'),
(299, 'The talent for being happy is appreciating and liking what you have, instead of what you don\'t have.', 'Woody Allen'),
(300, 'Time is nature\'s way of keeping everything from happening at once.', 'Woody Allen')
	");
	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(301, 'Eighty percent of success is showing up.', 'Woody Allen'),
(302, 'Nobody is bored when he is trying to make something that is beautiful, or to discover something that is true.', 'William Ralph Inge'),
(303, 'The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails.', 'John C. Maxwell'),
(304, 'We must be silent before we can listen.\r\nWe must listen before we can learn.\r\nWe must learn before we can prepare.\r\nWe must prepare before we can serve.\r\nWe must serve before we can lead.', 'William Arthur Ward'),
(305, 'To make mistakes is human; to stumble is commonplace; to be able to laugh at yourself is maturity.', 'William Arthur Ward'),
(306, 'When we seek to discover the best in others, we somehow bring out the best in ourselves.', 'William Arthur Ward'),
(307, 'We are more than what we do, much more than what we accomplish, far more than what we possess.', 'William Arthur Ward'),
(308, 'Optimists enrich the present, enhance the future, challenge the improbable and attain the impossible.', 'William Arthur Ward'),
(309, 'Do what you can, with what you have, where you are.', 'Theodore Roosevelt'),
(310, 'We are face to face with our destiny and we must meet it with high and resolute courage.', 'Theodore Roosevelt'),
(311, 'Far and away the best prize that life offers is the chance to work hard at work worth doing.', 'Theodore Roosevelt'),
(312, 'No one cares how much you know, until they know how much you care.', 'Theodore Roosevelt'),
(313, 'Courage is not having the strength to go on; it is going on when you donâ€™t have the strength.', 'Theodore Roosevelt'),
(314, 'We must realize that greatness is the fruit of toil and sacrifice and high courage.', 'Theodore Roosevelt'),
(315, 'The most important things are the hardest to say.', 'Stephen King'),
(316, 'The scariest moment is always just before you start.', 'Stephen King'),
(317, 'You can, you should, and if youâ€™re brave enough to start, you will.', 'Stephen King'),
(318, 'Hope is a good thing, maybe the best of things, and no good thing ever dies.', 'Stephen King'),
(319, 'The quality of a leader is reflected in the standards they set for themselves.', 'Ray Kroc'),
(320, 'Happiness is not a tangible thing, itâ€™s a byproduct â€“ a byproduct of achievement.', 'Ray Kroc'),
(321, 'If you work just for money, youâ€™ll never make it, but if you love what youâ€™re doing and you always put the customer first, success will be yours.', 'Ray Kroc'),
(322, 'Look after the customers and the business will take care of itself.', 'Ray Kroc'),
(323, 'Adversity can strengthen you if you have the will to grind it out.', 'Ray Kroc'),
(324, 'Life was meant to be lived, and curiosity must be kept alive. One must never, for whatever reason, turn his back on life.', 'Eleanor Roosevelt'),
(325, 'The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.', 'Eleanor Roosevelt'),
(326, 'You have to accept whatever comes, and the only important thing is that you meet it with the best you have to give.', 'Eleanor Roosevelt'),
(327, 'Never mistake knowledge for wisdom. One helps you make a living; the other helps you make a life.', 'Eleanor Roosevelt'),
(328, 'Always aim at complete harmony of thought and word and deed. Always aim at purifying your thoughts and everything will be well.', 'Mahatma Gandhi'),
(329, 'Freedom is not worth having if it does not include the freedom to make mistakes.', 'Mahatma Gandhi'),
(330, 'In the attitude of silence the soul finds the path in a clearer light, and what is elusive and deceptive resolves itself into crystal clearness.', 'Mahatma Gandhi'),
(331, 'Our life is a long and arduous quest after Truth.', 'Mahatma Gandhi'),
(332, 'You must be the change you want to see in the world.', 'Mahatma Gandhi'),
(333, 'Doing the right thing is more important than doing the thing right.', 'Peter Drucker'),
(334, 'There is nothing quite so useless as doing with great efficiency something that should not be done at all.', 'Peter Drucker'),
(335, 'Plans are only good intentions unless they immediately degenerate into hard work.', 'Peter Drucker'),
(336, 'Knowledge has to be improved, challenged, and increased constantly, or it vanishes.', 'Peter Drucker'),
(337, 'Follow effective action with quiet reflection. From the quiet reflection will come even more effective action.', 'Peter Drucker'),
(338, 'Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.', 'Swami Vivekananda'),
(339, 'Happiness lies in the joy of achievement and the thrill of creative effort.', 'Franklin D. Roosevelt'),
(340, 'Success is nothing more than a few simple disciplines, practiced every day.', 'Jim Rohn'),
(341, 'Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.', 'Booker T. Washington'),
(342, 'The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.', 'Confucius'),
(343, 'Our greatest glory is not in never falling, but in rising every time we fall.', 'Confucius'),
(344, 'When it is obvious that the goals cannot be reached, don\'t adjust the goals, adjust the action steps.', 'Confucius'),
(345, 'Wherever you go, go with all your heart.', 'Confucius'),
(346, 'Do not overestimate the competition and underestimate yourself. You are better than you think.', 'Tim Ferriss'),
(347, 'Tomorrow becomes never. No matter how small the task, take the first step now!', 'Tim Ferriss'),
(348, 'It isnâ€™t enough to think outside the box. Thinking is passive. Get used to acting outside the box.', 'Tim Ferriss'),
(349, 'What we fear doing most is usually what we most need to do.', 'Tim Ferriss'),
(350, 'Many a false step was made by standing still.', 'Tim Ferriss')
	");
	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(351, 'Don\'t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you.', 'Mary Kay Ash'),
(352, 'A mediocre idea that generates enthusiasm will go further than a great idea that inspires no one.', 'Mary Kay Ash'),
(353, 'For every failure, there\'s an alternative course of action. You just have to find it. When you come to a roadblock, take a detour.', 'Mary Kay Ash'),
(354, 'Those who are blessed with the most talent don\'t necessarily outperform everyone else. It\'s the people with follow-through who excel.', 'Mary Kay Ash'),
(355, 'We must have a theme, a goal, a purpose in our lives.', 'Mary Kay Ash'),
(356, 'Happiness is not something you postpone for the future; it is something you design for the present.', 'Jim Rohn'),
(357, 'You must take personal responsibility. You cannot change the circumstances, the seasons, or the wind, but you can change yourself.', 'Jim Rohn'),
(358, 'If you are not willing to risk the unusual, you will have to settle for the ordinary.', 'Jim Rohn'),
(359, 'The walls we build around us to keep sadness out also keeps out the joy.', 'Jim Rohn'),
(360, 'Sometimes all you need to open the door is just one more good idea.', 'Jim Rohn'),
(361, 'Success is doing ordinary things extraordinarily well.', 'Jim Rohn'),
(362, 'Success is...\r\nknowing your purpose in life,\r\ngrowing to reach your maximum potential, and\r\nsowing seeds that benefit others.', 'John C. Maxwell'),
(363, 'The greatest mistake we make is living in constant fear that we will make one.', 'John C. Maxwell'),
(364, 'If you start today to do the right thing, you are already a success even if it doesnâ€™t show yet.', 'John C. Maxwell'),
(365, 'Small disciplines repeated with consistency every day lead to great achievements gained slowly over time.', 'John C. Maxwell'),
(366, 'Life is now in session. Are you present?', 'John C. Maxwell'),
(367, 'Your vision will become clear only when you look into your heart. Who looks outside, dreams. Who looks inside, awakens.', 'Carl Jung'),
(368, 'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', 'David Brinkley'),
(369, 'If you change the way you look at things, the things you look at change.', 'Dr. Wayne Dyer'),
(370, 'You have everything you need for complete peace and total happiness right now.', 'Dr. Wayne Dyer'),
(371, 'The more you see yourself as what you\'d like to become, and act as if what you want is already there, the more you\'ll activate those dormant forces that will collaborate to transform your dream into your reality.', 'Dr. Wayne Dyer'),
(372, 'You don\'t need to be better than any one else, you just need to be better than you used to be.', 'Dr. Wayne Dyer'),
(373, 'You cannot always control what goes on outside. But you can always control what goes on inside.', 'Dr. Wayne Dyer'),
(374, 'Each experience in your life was absolutely necessary in order to have gotten you to the next place, and the next place, up to this very moment.', 'Dr. Wayne Dyer'),
(375, 'Go for it now. The future is promised to no one.', 'Dr. Wayne Dyer'),
(376, 'The state of your life is nothing more than a reflection of the state of your mind.', 'Dr. Wayne Dyer'),
(377, 'What comes out of you when you are squeezed is what is inside of you.', 'Dr. Wayne Dyer'),
(378, 'Doing what you love is the cornerstone of having abundance in your life.', 'Dr. Wayne Dyer'),
(379, 'Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.', 'Dr. Wayne Dyer'),
(380, 'Don\'t die with the music still in you.', 'Dr. Wayne Dyer'),
(381, 'It\'s never crowded along the extra mile.', 'Dr. Wayne Dyer'),
(382, 'Begin with the end in mind. Start with the end outcome and work backwards to make your dream possible.', 'Dr. Wayne Dyer'),
(383, 'Today is a most unusual day, because we have never lived it before; we will never live it again; it is the only day we have.', 'William Arthur Ward'),
(384, 'Adversity causes some men to break; others to break records.', 'William Arthur Ward'),
(385, 'If you can imagine it, you can achieve it; if you can dream it, you can become it.', 'William Arthur Ward'),
(386, 'Nothing limits achievement like small thinking; nothing expands possibilities like unleashed imagination.', 'William Arthur Ward'),
(387, 'Three keys to abundant living: caring about others; daring for others; sharing with others.', 'William Arthur Ward'),
(388, 'Opportunities are like sunrises: If you wait too long, you miss them.', 'William Arthur Ward'),
(389, 'You have to grow from the inside out. None can teach you, none can make you spiritual. There is no other teacher but your own soul.', 'Swami Vivekananda'),
(390, 'We are what our thoughts have made us; so take care about what you think. Words are secondary. Thoughts live; they travel far.', 'Swami Vivekananda'),
(391, 'All the powers in the universe are already ours. It is we who have put our hands before our eyes and cry that it is dark.', 'Swami Vivekananda'),
(392, 'The whole secret of existence is to have no fear. Never fear what will become of you, depend on no one. Only the moment you reject all help are you freed.', 'Swami Vivekananda'),
(393, 'Do not wait for extraordinary circumstances to do good action; try to use ordinary situations.', 'John Paul Richter'),
(394, 'Courage consists not in blindly overlooking danger, but in seeing it, and conquering it.', 'John Paul Richter'),
(395, 'Gratitude bestows reverence, allowing us to encounter everyday epiphanies, those transcendent moments of awe that change forever how we experience life and the world.', 'John Milton'),
(396, 'Nothing profits more than self-esteem, grounded on what is just and right.', 'John Milton'),
(397, 'The superior man acquaints himself with many sayings of antiquity and many deeds of the past, in order to strengthen his character thereby.', 'John Milton'),
(398, 'We have an infinite amount to learn both from nature and from each other.', 'John Glenn'),
(399, 'The only thing we have to fear is fear itself.', 'Franklin D. Roosevelt'),
(400, 'It isn\'t sufficient just to want - you\'ve got to ask yourself what you are going to do to get the things you want.', 'Franklin D. Roosevelt')
	");
	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(401, 'The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt'),
(402, 'Everything that irritates us about others can lead us to an understanding of ourselves.', 'Carl Jung'),
(403, 'The creation of something new is not accomplished by the intellect but by the play instinct acting from inner necessity. The creative mind plays with the objects it loves.', 'Carl Jung'),
(404, 'Mistakes are, after all, the foundations of truth, and if a man does not know what a thing is, it is at least an increase in knowledge if he knows what it is not.', 'Carl Jung'),
(405, 'Success in life is founded upon attention to the small things rather than to the large things; to the every day things nearest to us rather than to the things that are remote and uncommon.', 'Booker T. Washington'),
(406, 'Excellence is to do a common thing in an uncommon way.', 'Booker T. Washington'),
(407, 'Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.', 'Harriet Tubman'),
(408, 'There is no passion to be found playing small - in settling for a life that is less than the one you are capable of living.', 'Nelson Mandela'),
(409, 'Every great dream begins with a dreamer.', 'Harriet Tubman'),
(410, 'With out passion you don\'t have energy, with out energy you have nothing.', 'Donald Trump'),
(411, 'Do it no matter what. If you believe in it, it is something very honorable. If somebody around you or your family does not understand it, then that\'s their problem. But if you do have a passion, an honest passion, just do it.', 'Mario Andretti'),
(412, 'If passion drives you, let reason hold the reins.', 'Benjamin Franklin'),
(413, 'Acknowledging the good that you already have in your life is the foundation for all abundance.', 'Eckhart Tolle'),
(414, 'Always bear in mind that your own resolution to succeed is more important than any other one thing.', 'Abraham Lincoln'),
(415, 'Nothing great was ever achieved without enthusiasm.', 'Ralph Waldo Emerson'),
(416, 'If your dreams don\'t scare you, they\'re too small.', 'Richard Branson'),
(417, 'Create the highest, grandest vision possible for your life, because you become what you believe.', 'Oprah Winfrey'),
(418, 'Do something wonderful, people may imitate it.', 'Albert Schweitzer'),
(419, 'If you want to lift yourself up, lift up someone else.', 'Booker T. Washington'),
(420, 'Day by day we should weigh what we have granted to the spirit of the world against what we have denied to the spirit of Jesus, in thought and especially in deed.', 'Albert Schweitzer'),
(421, 'Associate yourself with people of good quality, for it is better to be alone than in bad company.', 'Booker T. Washington'),
(422, 'Nothing ever comes to one, that is worth having, except as a result of hard work.', 'Booker T. Washington'),
(423, 'People have the illusion that all over the world, all the time, all kinds of fantastic things are happening. When in fact, over most of the world, most of the time, nothing is happening.', 'David Brinkley'),
(424, 'It is better to lead from behind and to put others in front, especially when you celebrate victory when nice things occur. You take the front line when there is danger. Then people will appreciate your leadership.', 'Nelson Mandela'),
(425, 'A good head and a good heart are always a formidable combination.', 'Nelson Mandela'),
(426, 'It always seems impossible until its done.', 'Nelson Mandela'),
(427, 'There is nothing like returning to a place that remains unchanged to find the ways in which you yourself have altered.', 'Nelson Mandela'),
(428, 'There can be no keener revelation of a society\'s soul than the way in which it treats its children.', 'Nelson Mandela'),
(429, 'Even if you have a terminal disease, you don\'t have to sit down and mope. Enjoy life and challenge the illness that you have.', 'Nelson Mandela'),
(430, 'It is wise to persuade people to do things and make them think it was their own idea.', 'Nelson Mandela'),
(431, 'The more you praise and celebrate your life, the more there is in life to celebrate.', 'Oprah Winfrey'),
(432, 'Be thankful for what you have; you\'ll end up having more. If you concentrate on what you don\'t have, you will never, ever have enough.', 'Oprah Winfrey'),
(433, 'Passion is energy. Feel the power that comes from focusing on what excites you.', 'Oprah Winfrey'),
(434, 'The biggest adventure you can take is to live the life of your dreams.', 'Oprah Winfrey'),
(435, 'Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.', 'Oprah Winfrey'),
(436, 'If you want to accomplish the goals of your life, you have to begin with the spirit.', 'Oprah Winfrey'),
(437, 'Doing the best at this moment puts you in the best place for the next moment.', 'Oprah Winfrey'),
(438, 'What God intended for you goes far beyond anything you can imagine.', 'Oprah Winfrey'),
(439, 'The greatest discovery of all time is that a person can change his future by merely changing his attitude.', 'Oprah Winfrey'),
(440, 'Understand that the right to choose your own path is a sacred privilege. Use it. Dwell in possibility.', 'Oprah Winfrey'),
(441, 'The thing you fear most has no power. Your fear of it is what has the power. Facing the truth really will set you free.', 'Oprah Winfrey'),
(442, 'Business opportunities are like buses, there\'s always another one coming.', 'Richard Branson'),
(443, 'You don\'t learn to walk by following rules. You learn by doing, and by falling over.', 'Richard Branson'),
(444, 'Do not be embarrassed by your failures, learn from them and start again.', 'Richard Branson'),
(445, 'One thing is certain in business. You and everyone around you will make mistakes.', 'Richard Branson'),
(446, 'A business has to be involving, it has to be fun, and it has to exercise your creative instincts.', 'Richard Branson'),
(447, 'An eye for an eye only ends up making the whole world blind.', 'Mahatma Gandhi'),
(448, 'Whatever you are, be a good one.', 'Abraham Lincoln'),
(449, 'Resolve to keep happy, and your joy and you shall form an invincible host against difficulties.', 'Helen Keller'),
(450, 'It is hard to fail, but it is worse never to have tried to succeed', 'Theodore Roosevelt')
	");
	$GLOBALS["wpdb"]->query("INSERT INTO ".$GLOBALS["autotweet_quotes_table"].
	"(quote_id, quote_text, quote_author) VALUES
(451, 'Anything worth doing is worth doing poorly until you can learn to do it well.', 'Zig Ziglar'),
(452, 'People cry, not because they are weak. It is because they\'ve been strong for too long.', 'Johnny Depp'),
(453, 'Follow your bliss and the universe will open doors for you where there were only walls.', 'Joseph Campbell'),
(454, 'Live as if you were living a second time, and as though you had acted wrongly the first time.', 'Victor Frankl'),
(455, 'Daring ideas are like chessmen moved forward. They may be beaten, but they may start a winning game.', 'Johann Wolfgang Von Goethe'),
(456, 'To be successful, grow to the point where one completely forgets himself; that is, to lose himself in a great cause.', 'Booker T. Washington'),
(457, 'We can\'t solve problems by using the same kind of thinking we used when we created them.', 'Albert Einstein'),
(458, 'Respect yourself and others will respect you.', 'Confucius'),
(459, 'For every minute you are angry you lose sixty seconds of happiness.', 'Ralph Waldo Emerson'),
(460, 'Stop being who you were and become who you are.', 'Paulo Coelho'),
(461, 'We are shaped and fashioned by what we love.', 'Johann Wolfgang Von Goethe'),
(462, 'You must either modify your dreams or magnify your skills.', 'Jim Rohn'),
(463, 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment', 'Ralph Waldo Emerson'),
(464, 'It isn\'t what you have, or who you are, or where you are, or what you are doing that makes you happy or unhappy. It is what you think about.', 'Dale Carnegie'),
(465, 'You have to learn the rules of the game. And then you have to play better than anyone else.', 'Albert Einstein'),
(466, 'Live as if you were to die tomorrow. Learn as if you were to live\r\nforever.', 'Mahatma Gandhi'),
(467, 'Don\'t join an easy crowd; you won\'t grow. Go where the expectations and the demands to perform are high.', 'Jim Rohn'),
(468, 'Character develops itself in the stream of life.', 'Johann Wolfgang Von Goethe'),
(469, 'Fresh activity is the only means of overcoming adversity.', 'Johann Wolfgang Von Goethe'),
(470, 'In art the best is good enough.', 'Johann Wolfgang Von Goethe'),
(471, 'As soon as you trust yourself, you will know how to live.', 'Johann Wolfgang Von Goethe'),
(472, 'To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.', 'Johann Wolfgang Von Goethe'),
(473, 'Magic is believing in yourself, if you can do that, you can make anything happen.', 'Johann Wolfgang Von Goethe'),
(474, 'The person born with a talent they are meant to use will find their greatest happiness in using it.', 'Johann Wolfgang Von Goethe'),
(475, 'Everything is hard before it is easy.', 'Johann Wolfgang Von Goethe'),
(476, 'Do not go where the path may lead, go instead where there is no path and leave a trail.', 'Ralph Waldo Emerson'),
(477, 'When it is dark enough, you can see the stars.', 'Ralph Waldo Emerson'),
(478, 'The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.', 'Ralph Waldo Emerson'),
(479, 'Dare to live the life you have dreamed for yourself. Go forward and make your dreams come true.', 'Ralph Waldo Emerson'),
(480, 'Once you make a decision, the universe conspires to make it happen.', 'Ralph Waldo Emerson'),
(481, 'All life is an experiment. The more experiments you make the better.', 'Ralph Waldo Emerson')");

?>
